version: "3"

services:
  zookeeper:
    image: zookeeper:3.4.12
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      app_net:
        ipv4_address: 172.16.121.2

  mesos-master:
    image: mesosphere/mesos-master:1.5.0
    privileged: true
    hostname: localhost
    ports:
      - "5050:5050"
    networks:
      app_net:
        ipv4_address: 172.16.121.3
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      MESOS_ZK: zk://zookeeper:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
#      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: localhost
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LOG_DIR: /var/log/mesos
      LIBPROCESS_IP: 172.16.121.3

  mesos-slave:
    image: mesosphere/mesos-slave:1.5.0
    privileged: true
    hostname: localhost
    ports:
      - "5051:5051"
    networks:
      app_net:
        ipv4_address: 172.16.121.4
    links:
      - zookeeper:zookeeper
      - mesos-master:master.mesos
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_CONTAINERIZERS: docker
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: localhost
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
      LIBPROCESS_IP: 172.16.121.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  marathon:
    image: mesosphere/marathon:v1.5.9
    entrypoint:
      - ./bin/start
      - --disable_ha
    hostname: localhost
    ports:
     - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.16.121.5
    links:
      - zookeeper
      - mesos-master
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-slave
    environment:
      - MARATHON_ZK=zk://zookeeper:2181/marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - LIBPROCESS_IP=172.16.121.5

  jenkins:
    image: jenkins/jenkins:2.150-alpine
    hostname: localhost
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
    networks:
      app_net:
        ipv4_address: 172.16.121.6

  jenkins-slave:
    image: jenkinsci/ssh-slave
    hostname: localhost
    networks:
      app_net:
        ipv4_address: 172.16.121.8

  docker-registry:
    image: registry
    hostname: localhost
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.16.121.7

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.121.0/24

